#+title: Demo - Web Foundations
#+author: John Zimmerman
#+email: jzimmerman3@madisoncollege.edu
#+date: 2026:01:22

* Demo - Web Foundations

** The Beginning

*Tim Berners-Lee*, a british scientist at CERN, invented to World Wide Web in 1989. Back then, the web was conceived and developed to meet the demand for automatic information-sharing between scientists in universities and institutions.

** How the Internet Works

Very simply, On the client side there is a brower like Chrome of Firefox and it pushes requests to the server, and the server sends a response back to the browser. Somewhere down the line, the browser creates the *Document Object Model* (DOM) and the data (HTML/CSS) shows up visually on the screen.

** The Trinity of Web Development

The three main components of web developnment is *HTML*, *CSS*, and *JavaScript*.

- HTML :: HyperText Markup Language
  - Builds the /structure/ or skeleton of website
  - Think of a frame on a house
- CSS :: Cascadimg Style Sheets
  - Builds the /presentation/ of a website
  - Think of the decorations on a house
- JS :: JavaScript
  - Builds the /behavior/ and interactivity of a website
  - Like the appliances of a house
    
** The Basic Structure of a Webpage

#+begin_src 
<!DOCTYPE html> 
<html> 
<head> 
  <title>Jen's Kitchen</title> 
</head> 

<body> 
<h1>This is a heading</h1>
  
<h2> this is another heading</h2>

<p>This is a paragraph</p>

<br> 

</body> 
</html> 
#+end_src

** HTML Structure

- Tag :: Refers to the descriptor or type for content. Example <p>, <h1>, etc.
- Content :: Refers to the /stuff/ in between the angle brackets of a tag.
- Attribute :: Goes inside of a tag, used to add clarity and nuance to an element.
- Value :: Content for the attribute.
- Element :: The tag and the content together is the element.

If a tag doesn't have content, it's considered a *self-closing tag*. All other tags need a /closing tag/. Example. </p>, </h1>, etc.

#+begin_src 
// examples here...
#+end_src


** WWW

For websites, we need a website server. This means software that handles HTTP or HTTPS. Servers job is to /serve up/ documents.

** IP Addresses

#+begin_src 

- Protocol :: https://
- Host name :: www.
- Domain Name :: Name of the site
- Dir path :: /directories/
- Doc :: absolute path - index.html

https://www.nameofsite/directories/index.html
  
#+end_src

** Default files

The index.html is usually the file in the root of the directory and is the main document for the webpage. If you don't specify a path, it will default to index.html.



** Internet vs Web

Not to be pedantic, but the *internet* and the *web* are not technically the same thing. The internet is an international network of connected computers. No company /owns/ the internet, it's more of a cooperative effort governed by a system of standards and rules. The purpose of connecting computers of course, is to share information. The web (orginally called the "World Wide Web") is just one of those ways information is shared over the internet.
