#+title: Unit 1 Review
#+author: John Zimmerman
#+email: jzimmerman3@madisoncollege.edu
#+date: 2026:01:21

* Learning Unit 3-1: Conversions

** Percents

Like fractions and decimals, *percents* describe parts of a whole. The word /percent/ means "per 100", and the percent symbol (~%~) indicates hundreths (division by 100). Percents are the result of expressing numbers as part of 100.

** Converting Decimals to Percents

- Step 1 :: Move the decimal point two places to the right. This represents multiplying by 100. If necessary, add zeros. This rule is also used for whole numbers and mixed decimals.
- Step 2 :: Add the percent symbol at the end of the number.

*** Examples

- $0.49 = 49%$
- $0.80 = 80%$
- $8.00 = 800%$
- $0.007 = 0.7%$

** Rounding Percents

The rules for rounding percents isn't necessarily universal, but these will be the rules for this class:

- Step 1 :: Only round once you a percentage. Make sure to convert from fractions or decimals first.
- Step 2 :: When rounding, you want the digit to the right of the digit in question to be 5 or greater. Then, you can round that identified digit up.
- Step 3 :: Delete digits to the right of the identified digit.

*** Examples

- $\frac{18}{55}$ = 32.727272... *rounded*: $32.73$
- $\frac{2}{3}$ = .66666666... *rounded*: $.67$

** Converting Percents to Decimals

To convert percents to decimals, just reverse what we learned for converting decimals to percents.

- Step 1 :: Drop the percent symbol
- Step 2 :: Move the decimal point two places left. This is the same as dividing by 100. If necessary, add zeros.

** Converting Fractions to Percents

When fractions have denominators of 100, it's fairly simple to convert it a percent. If it doesn't here are the steps.

- Step 1 :: Divide the numerator by the denominator to convert the fraction to a decimal.
- Step 2 :: Move the decimal point two places to the right, don't forget to add the percent sign.

** Converting Percents to Fractions

You can write any percent as a fraction whose denominator is 100.

- Step 1 :: Drop the percent symbol.
- Step 2 :: Multiply the number by $\frac{1}{100}$.
- Step 3 :: Reduce to lowest terms.

*** Example

Convert 76% to a fraction.

- Step 1 :: 76% = $\frac{76}{100}$
- Step 2 :: *Reduce*: $\frac{76}{100} = \frac{19}{25}$

** Converting a Mixed or Decimal Percent to a Fraction

- Step 1 :: Drop the percent symbol.
- Step 2 :: Change the mixed percent to an improper fraction.
- Step 3 :: Multiply the number by $\frac{1}{100}$

*** Example

Convert $12\frac{1}{2}$ % to a fraction:

- Step 1 :: Convert $12\frac{1}{2}$ % to an improper fraction.
  - $(2 * 12) + 1 = 25$
  - $\frac{25}{2}$
- Step 2 :: Multiply $\frac{25}{2} * $\frac{1}{100}$
  - *Equals*: $\frac{25}{200}$
- Step 3 :: *Reduce*: $\frac{25}{200}$ = $\frac{1}{8}$

* Learning Unit 3-2: Application of Percents-Portion Formula

- Base */(B)/* :: The *base* is the beginning whole quantity or value (100%).
- Rate */(R)/* :: The *rate* is a percent, decimal, or fraction that indicates the part of the base that you must calculate. Look for the percent sign to identify the rate.
- Portion */(P)/* :: The *portion* is the amount or part that results from $base * rate$.

** Solving Percents with the Portion Formula

*** TODO practice these word problems!!!! 
SCHEDULED: <2026-01-21 Wed> DEADLINE: <2026-01-22 Thu>

* Basic Equation Solving Procedures

- Expression :: A meaningful combination of letters and numbers called /terms/. Operational signs such as + or - within an expression. Expressions help to define the relationship between the operands.
- Formula :: A formula is an /equation for expressing a word concept. From last weeks lesson, we learned about the ~Base * Rate = Portion~ formula. Another formula is the simple interest formula, ~Interest = Principal * Rate * Time~.
- Variable  :: A variable stands for a number. It is a way to represent the number of an *unknown* for which we are solving for. Numbers that are not variables are considered *constants* or *knowns*.
- Equation :: An equation is an expression where both sides of the ~=~ sign are equal. This means you may have to /adjust/ for the right answer.
- PEMDAS :: An acronym for the *orders of operations*, i.e. Parentheses, Expontent, Multiplication & Division, and Addition & and Subtraction.
- Porportion :: A proportion is when two *ratios* are equal.
  - The easiest way to solve for proportions is /cross multiplication/.

*Example*:

$\frac{3}{6} = \frac{1}{2}$ is the same as $3 * 2 = 6 * 1$

- Coefficient :: A number in front of a variable is called a coefficient.

* Chapter 5 - Business Statistics Notes

** Graphs

- Bar Graph :: These types of graphs assist with visualizing changes that have occured over a period of time. This is especially true when the same type of data is repreatedly studied.

- Line Graph :: Shows trends over a period of time. Often separate lines are drawn to show the comparison between two or more trends.

- Circle Graph :: Also called a /pie chart/, these are helpful for showing the relationship of parts to a whole. The entire circle represents 100% or 360°.

*Index numbers* express the relative changes in a variable compared with some base with is taken as 100. Index numbers function as percents and are calculated like percents. Frequently businesses will use index numbers to make comparisons of a current price relative to a given year.

*** Price Relative

If you want to compare the current cost of something against what it was previously, you can use the *price relative* formula. The way it works is by taking the current price /divided by/ a target previous year (the base year), and then /multiply by/ 100.

- $c / b * 100 =$ price relative

** Mean, Median, and Mode

The first thing to do when working with data points for statistics is first to identify whether the data represents a *population* or a *sample*.

- Population :: Data that represent an entire group being studied.

- Sample :: A portion or part of the population being studied. A sample is *random* if every point in your population has the same chance of being selected.

*** Mean

The mean is a value that represents the center of a set of numbers by balancing them evenly. Its not about middle or most common, but /equal distribution/. To calculate mean, you take the sum of all the values and /divide by/ the number of values.

***** Example - Find the *mean*: (2,2,3,5,6,5,10,17).

- $(2+2+3+5+6+5+10+17)/8=6.25$


*** Weighted Mean

When values appear more than once, you can calculate a weighted mean by /multiplying/ the value against the the amount of times it appears (frequency). You add those numbers up and /divide by/ the sum of frequencies to get your weighted mean.

***** Example - Find the *weighted mean*: (2,2,3,5,6,5,10,17).

- $((2*2)+(3*1)+(5*2)+(6*1)+(10*1)+(17*1))/(2+1+2+1+1+1)$

- $(4+3+10+6+10+17)/8$

- $50/8=6.25$

*** Median

The median is another measurement that indicates the /center/ of the data. For instance, lets say you have numbers (1,2,2,3,4,2,1,20). When calculating the *arithmetic mean*, the number 20 will throw a wrench into your calculation and skew the data depending on what you're looking for.

***** Example - Find the *median*: (1,2,2,1,3,4,2,1,20).

- Arrange values from smallest to largest in an *ordered array* - (1,1,1,2,2,2,3,4,20).

- Find the middle value:

  - Odd numbers :: median is the middle of the ordered array.

  - Even numbers :: median is the average of the two middle values.

  - Answer :: 2

*** Mode

The mode is the measurement that also records values. In a series of numbers, the value that occurs most often is the mode. So in an array of (1,2,3,3,4,5,2,3,4,5,1,1,4,1,1), the *mode* is 1 because it appears most in the array. You can have either no mode, or more than one mode.

** Measures of Dispersion

A measure of dispersion is a number that describes how the numbers of a set of data are spread out or dispersed.

- Range :: The difference between the highest and lowest values in a group is called the *range*. The range between 1 and 10 is $10-1=9$. If the set of numbers is continuous with no end, the range is *undefined*. If the set has all the same values, the range is 0.

*** Variance and Standard Deviation

Standard deviation is used to find the spread of data from the mean. Variance is used to calculate the standard deviation.

- Variance :: The arithmetic mean of the squared deviations from the mean.

- Standard Deviation :: Measures the spread of data /around/ the mean.

*** Calculating Standard Deviation and Variance

1. Find the mean of the set of data.
2. Subtract the mean from each data point to find each deviation.
3. Square each deviation
4. Sum all squared deviations
5. Divide the sum of the squared deviations by $n-1$, where $n$ equals the number of data points. (This is the variance).
6. Square root the variance to get the standard deviation.

The variance is the square of the standard deviation and is calculated by taking the average of the squared differences from the mean. The standard deviation is simply the square root of the variance.

*** Normal Distribution

A *normal distribution is a bell-shaped distribution where data is spread symmetrically about the mean. Meaning that 50% of the observations fall below the mean and 50% of the observations fall above the mean.

- Emprical Rule :: Also known as the *Three Sigma Rule*, states that approximately:

  - 68% of the /observations/ will fall within ± 1 standard deviation of the mean (34% on either side of the mean)

  - 95% will fall within ± 2 standard deviations of the mean (13.5% outside 1 standard deviation on either side of the mean)

  - 99.7% will fall within ± 3 standard deviations of the mean (2.35% outside 2 standard deviations on either side of the mean)
  
